### ISSUE TITLE
Losing Authentication on Page Refresh

### ISSUE THREAD

**Issue by MartianK** [cjafet/angularjs-authentication-firebase#1]
Hi 
Would love to implement this but it appears to lose authentication on page refresh F5
(fine between routes)

Is there a method that authentication could be persistent

**Comment by cjafet** [comment]
Sure, @MartianK! I will look the code and get back to you, ok?

**Comment by cjafet** [comment]
Hi @MartianK! I have added firebase session persistence to the project and you can already pull the new files, ok? Any doubts, just let me know. 

Regards,

Carlos

**Comment by MartianK** [comment]
Hi Carlos

Thanks for all your efforts

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MartianK** [comment]
Hi Carlos

Tried the new package and can see you've added the session persistence in the authentication.js

However the auth package  fails to login at all now
 TypeError: Cannot read property 'SESSION' of undefined

Regards Martin
________________________________
From: Martin Knott
Sent: 08 October 2019 05:51
To: cjafet/angularjs-authentication-firebase <reply@reply.github.com>; cjafet/angularjs-authentication-firebase <angularjs-authentication-firebase@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [cjafet/angularjs-authentication-firebase] Losing Authentication on Page Refresh (#1)


Hi Carlos



Thanks for all your efforts



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10



________________________________

**Comment by cjafet** [comment]
Hi MartianK,

Thats because i forgot to update the firebase lib version in the index.html file from version 3.5.2 to 4.2.0, like this:

<script src="https://www.gstatic.com/firebasejs/4.2.0/firebase.js"></script>

Session is only available from this version on.

Sorry about that!

**Comment by MartianK** [comment]
Thanks Carlos
Works a charm on your downloaded app

i'll try and implement into my production app later and let you know

Thanks for all your efforts





________________________________

**Comment by cjafet** [comment]
That's great, MartianK!! Anything else, just let me know!!
